MVCAuctionPortal/Models/Coupon.cs
using System.ComponentModel.DataAnnotations;

namespace AuctionPortal.Models
{
    public class Coupon
    {
        [Key]
        [Required]
        public int CouponID { get; set; }

        [Required]
        [StringLength(10)]
        public string Name { get; set; }
        [Required]
        [Range(1, 100)]
        public int DiscountPercentage { get; set; }

        [Required]
        [StringLength(50)]
        public string Description { get; set; }


        [Required]
        public DateTime ExpireDate { get; set; }

        [Required] public int NumberOfUses { get; set; } = 0;

        public int UserId { get; set; }
        public virtual User User { get; set; }
    }
}

MVCAuctionPortal/Controllers/CouponController.cs
using AuctionPortal.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ServicesAndInterfacesLibary.Services;
using System.Security.Claims;

namespace MVCAuctionPortal.Controllers
{
    public class CouponController : Controller
    {
        private readonly ICouponService _couponService;

        public CouponController(ICouponService couponService)
        {
            _couponService = couponService;
        }
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(IFormCollection formCollection)
        {
            if (ModelState.IsValid)
            {
                Coupon coupon = new Coupon
                {
                    Name = formCollection["Name"],
                    Description = formCollection["Description"],
                    ExpireDate = DateTime.Parse(formCollection["ExpireDate"]),
                    DiscountPercentage = int.Parse(formCollection["DiscountPercentage"]),
                    NumberOfUses = int.Parse(formCollection["NumberOfUses"])

                };

                string userEmail = formCollection["UserEmail"];

                bool created = await _couponService.CreateUserCouponAsync(coupon, userEmail);
                if (created)
                {
                    return RedirectToAction("ListOfCoupons");
                }
                ModelState.AddModelError("UserEmail", "User not found with the provided email.");
            }
            return RedirectToAction("ListOfCoupons");
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult Edit(Coupon coupon)
        {
            _couponService.Update(coupon);
            return RedirectToAction("ListOfCoupons");
        }
        [AllowAnonymous]
        public async Task<IActionResult> ListOfCoupons()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var coupons = await _couponService.GetCouponsForUser(userId);
            return View(coupons.ToList());
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult Delete(int id)
        {
            _couponService.Delete(id);
            return RedirectToAction("ListOfCoupons");
        }
    }
}

MVCAuctionPortal/Views/Coupon/Create.cshtml
@model AuctionPortal.Models.Coupon

<form method="post" class="form-horizontal" role="form">
    @Html.AntiForgeryToken()
    <div class="form-group">
        <label for="Name" class="control-label col-md-2">Name:</label>
        <div class="col-md-10">
            <input type="text" id="Name" name="Name" class="form-control" />
        </div>
    </div>

    <div class="form-group">
        <label for="Description" class="control-label col-md-2">Description:</label>
        <div class="col-md-10">
            <textarea id="Description" name="Description" class="form-control"></textarea>
        </div>
    </div>

    <div class="form-group">
        <label for="ExpireDate" class="control-label col-md-2">Expire Date:</label>
        <div class="col-md-10">
            <input type="date" id="ExpireDate" name="ExpireDate" class="form-control"  />
        </div>
    </div>

    <div class="form-group">
        <label for="NumberOfUses" class="control-label col-md-2">Discount %</label>
        <div class="col-md-10">
            <input type="number" id="DiscountPercentage" name="DiscountPercentage" class="form-control" />
        </div>
    </div>

    <div class="form-group">
        <label for="NumberOfUses" class="control-label col-md-2">Number Of Uses:</label>
        <div class="col-md-10">
            <input type="number" id="NumberOfUses" name="NumberOfUses" class="form-control"  />
        </div>
    </div>

    <div class="form-group">
        <label for="UserEmail" class="control-label col-md-2">User Email:</label>
        <div class="col-md-10">
            <input type="email" id="UserEmail" name="UserEmail" class="form-control" required />
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button type="submit" class="btn btn-default">Save</button>
        </div>
    </div>
</form>

MVCAuctionPortal/Views/Coupon/Edit.cshtml
@model AuctionPortal.Models.Coupon

<form method="post" action="@Url.Action("Edit", "Coupon")" class="form-horizontal" role="form">
    <input type="hidden" name="CouponID" value="@Model.CouponID" />

    <div class="form-group">
        <label for="Name" class="control-label col-md-2">Name:</label>
        <div class="col-md-10">
            <input type="text" id="Name" name="Name" class="form-control" value="@Model.Name" />
        </div>
    </div>

    <div class="form-group">
        <label for="Description" class="control-label col-md-2">Description:</label>
        <div class="col-md-10">
            <textarea id="Description" name="Description" class="form-control">@Model.Description</textarea>
        </div>
    </div>

    <div class="form-group">
        <label for="ExpireDate" class="control-label col-md-2">Expire Date:</label>
        <div class="col-md-10">
            <input type="date" id="ExpireDate" name="ExpireDate" class="form-control" value="@Model.ExpireDate.ToString("yyyy-MM-dd")" />
        </div>
    </div>

    <div class="form-group">
        <label for="NumberOfUses" class="control-label col-md-2">Number of Uses:</label>
        <div class="col-md-10">
            <input type="number" id="NumberOfUses" name="NumberOfUses" class="form-control" value="@Model.NumberOfUses" />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button type="submit" class="btn btn-default">Save</button>
        </div>
    </div>
</form>

MVCAuctionPortal/Views/Coupon/ListOfCoupons.cshtml
@model IEnumerable<AuctionPortal.Models.Coupon>

<table class="table table-striped table-bordered">
    <thead>
    <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Expire Date</th>
        <th>Number of Uses</th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var coupon in Model)
    {
        <tr>
            <td>@coupon.Name</td>
            <td>@coupon.Description</td>
            <td>@coupon.ExpireDate.ToShortDateString()</td>
            <td>@coupon.NumberOfUses</td>
            <td>
                <a href="@Url.Action("Edit", "Coupon", new { id = coupon.CouponID })" class="btn btn-primary">Edit</a>
                <form method="post" action="@Url.Action("Delete", "Coupon", new { id = coupon.CouponID })" onsubmit="return confirm('Are you sure you want to delete this item?');" style="display:inline;">
                    @Html.AntiForgeryToken()
                    <input type="submit" value="Delete" class="btn btn-danger" />
                </form>
            </td>
        </tr>
    }
    </tbody>
</table>