MVCAuctionPortal/Models/Auction.cs
using MVCAuctionPortal.Models;
using System.ComponentModel.DataAnnotations;

namespace AuctionPortal.Models
{
    public class Auction
    {
        [Key]
        [Required]
        public int AuctionID { get; set; }
        public string Title { get; set; }
        public DateTime DateOfIssue { get; set; }
        public DateTime? EndDate { get; set; }
        public decimal Price { get; set; }
        public int Pieces { get; set; }
        public int SubCategoryID { get; set; }
        public int ItemID { get; set; }
        public int WarrantyID { get; set; }
        public int UserID { get; set; }

        public string ImageURL { get; set; }

        public User User { get; set; }
        public SubCategory SubCategory { get; set; }
        public Item Item { get; set; }
        public Warranty Warranty { get; set; }
        public virtual ICollection<BasketAndAuction> BasketAndAuctions { get; set; }
        public virtual ICollection<Review> Reviews { get; set; }

    }
}

MVCAuctionPortal/Models/AuctionViewModel.cs
using AuctionPortal.Models;

namespace MVCAuctionPortal.Models;

public class AuctionViewModel
{
    public int ItemID { get; set; }
    public int WarrantyID { get; set; }
    public int SubCategoryID { get; set; }
    public string NewItemName { get; set; }
    public string NewItemDescription { get; set; }
    public string NewItemManufacturer { get; set; }
    public string NewItemCondition { get; set; }
    public string NewItemModel { get; set; }
    public string NewItemOther { get; set; }
    public string Title { get; set; }
    public DateTime? EndDate { get; set; }
    public decimal Price { get; set; }
    public int Pieces { get; set; }

    public string ImageURL { get; set; }
    public IEnumerable<Item> Items { get; set; }
    public IEnumerable<Warranty> Warranties { get; set; }
    public IEnumerable<SubCategory> SubCategories { get; set; }

}

MVCAuctionPortal/Controllers/AuctionController.cs
using AuctionPortal.Models;
using AuctionPortal.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MVCAuctionPortal.Models;
using MVCAuctionPortal.ViewModels;
using ServicesAndInterfacesLibary.Services;

namespace MVCAuctionPortal.Controllers
{
    public class AuctionController : Controller
    {
        private readonly ILogger<AuctionController> _logger;
        private readonly IAuctionService _auctionService;
        private readonly IItemService _itemService;
        private readonly IWarrantyService _warrantyService;
        private readonly ISubCategoryService _subCategoryService;
        private readonly IReviewService _reviewService;

        private readonly UserManager<User> _userManager;
        private readonly IOrderService _orderService;


        public AuctionController(ILogger<AuctionController> logger, IAuctionService auctionService,
            IItemService itemService, IWarrantyService warrantyService, ISubCategoryService subCategoryService,
            IReviewService reviewService, UserManager<User> userManager, IOrderService orderService)
        {
            _logger = logger;
            _auctionService = auctionService;
            _itemService = itemService;
            _warrantyService = warrantyService;
            _subCategoryService = subCategoryService;
            _reviewService = reviewService;
            _userManager = userManager;
            _orderService = orderService;
        }

        [AllowAnonymous]
        public IActionResult Index()
        {
            var allAuctions = _auctionService.GetAllAuctions();

            if (allAuctions == null || !allAuctions.Any())
            {
                return NotFound();
            }

            var auctionViewModels = allAuctions.Select(a => new AuctionAndWarrantyViewModel()
            {
                Auction = a,
                Warranty = _warrantyService.GetWarrantyById(a.WarrantyID)
            }).ToList();

            var random = new Random();
            auctionViewModels = auctionViewModels.OrderBy(a => random.Next()).ToList();

            var selectedAuctionViewModels = auctionViewModels.Take(6).ToList();

            return View(selectedAuctionViewModels);
        }


        [HttpGet]
        [Authorize(Roles = "Seller,Admin")]
        public ActionResult Create()
        {
            var viewModel = new AuctionViewModel
            {
                Items = _itemService.GetAllItems(),
                Warranties = _warrantyService.GetAllWarranties(),
                SubCategories = _subCategoryService.GetAllSubCategories()
            };
            return View(viewModel);
        }

        [HttpPost]
        [Authorize(Roles = "Seller,Admin")]

        public ActionResult Create(AuctionViewModel model)
        {
            var userId = _userManager.GetUserId(User);

            if (model.ItemID == 0 && !string.IsNullOrEmpty(model.NewItemName))
            {
                var newItem = new Item
                {
                    Name = model.NewItemName,
                    Description = model.NewItemDescription,
                    Manufacturer = model.NewItemManufacturer,
                    Condition = model.NewItemCondition,
                    Model = model.NewItemModel,
                    Other = model.NewItemOther
                };
                _itemService.Create(newItem);

                model.ItemID = newItem.ItemID;

            }

            {
                var newAuction = new Auction
                {
                    Title = model.Title,
                    EndDate = model.EndDate,
                    Price = model.Price,
                    Pieces = model.Pieces,
                    SubCategoryID = model.SubCategoryID,
                    ItemID = model.ItemID,
                    WarrantyID = model.WarrantyID,
                    ImageURL = model.ImageURL,
                    UserID= Int32.Parse(userId)
                };
                _auctionService.AddAuction(newAuction);



                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        [Authorize(Roles = "Seller,Admin")]
        public IActionResult Delete([FromRoute] int? id)
        {
            var auction = _auctionService.GetAuctionById(id);
            var userId = _userManager.GetUserId(User);

            if (auction.UserID != int.Parse(userId))
            {
                return Unauthorized(); 
            }

            _auctionService.DeleteAuction(id);
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Seller,Admin")]
        public IActionResult DeleteConfirmation(int id)
        {
            var auction = _auctionService.GetAuctionById(id);
            var userId = _userManager.GetUserId(User);

            if (auction.UserID != int.Parse(userId))
            {
                return Unauthorized(); 
            }

            if (auction == null)
            {
                return NotFound();
            }

            return View(auction);
        }

        [Authorize(Roles = "Seller,Admin")]
        public IActionResult Edit([FromRoute] int? id)
        {
            var userId = _userManager.GetUserId(User);

            if (userId == null)
            {
                return RedirectToAction("Login", "Account");
            }

            if (id == null)
            {
                var auctions = _auctionService.GetAuctionsForUser(int.Parse(userId));
                return View("SellerAuctionList", auctions);
            }
            else
            {
                var auction = _auctionService.GetAuctionById(id);

                if (auction.UserID != int.Parse(userId))
                {
                    return Unauthorized();
                }

                return View(auction);
            }
        }

        [Authorize(Roles = "Seller,Admin")]
        [HttpPost]
        public IActionResult Edit(Auction auction)
        {
            var userId = _userManager.GetUserId(User);

            if (auction.UserID != int.Parse(userId))
            {
                return Unauthorized();
            }

            _auctionService.UpdateAuction(auction);
            return RedirectToAction("UserPanel", "User");
        }

        [AllowAnonymous]
        [HttpGet]
        public IActionResult Details([FromRoute] int id)
        {
            var item = _itemService.GetItemById(id);
            var auction = _auctionService.GetAuctionByItemId(id);
            var reviews = _reviewService.GetReviewsByAuctionId(auction.AuctionID);
            ViewData["ImageUrl"] = auction.ImageURL;
            ViewData["Reviews"] = reviews;
            return View(item);
        }

        [AllowAnonymous]
        public IActionResult SubCategoryAuctionsList([FromRoute] int id)
        {
            var auctions = _auctionService.GetAuctionBySubCategory(id).ToList();

            var auctionViewModels = auctions.Select(a => new AuctionAndWarrantyViewModel()
            {
                Auction = a,
                Warranty = _warrantyService.GetWarrantyById(a.WarrantyID)
            }).ToList();

            var auctionAndWarrantyViewModels = auctions.Select(auction => new AuctionAndWarrantyViewModel
            {
                Auction = auction,
                Warranty = auction.Warranty != null
                    ? _warrantyService.GetWarrantyById(auction.Warranty.WarrantyID)
                    : null
            }).ToList();

            return View(auctionAndWarrantyViewModels);
        }


        [Authorize(Roles = "User,Seller,Admin")]

        [HttpGet]
        public IActionResult AddReviews(int orderId)
        {
            var order = _orderService.GetOrderDetailsById(orderId);
            if (order == null)
            {
                return NotFound();
            }

            var model = new OrderReviewsViewModel
            {
                OrderId = orderId,
                Reviews = order.OrderItems.Select(oi => new ReviewViewModel
                {
                    AuctionID = oi.Auction.AuctionID,
                    AuctionName = oi.Auction.Title
                }).ToList()
            };

            return View(model);
        }



        [Authorize(Roles = "User,Seller,Admin")]
        [HttpPost]
        public IActionResult AddReviews(OrderReviewsViewModel model)
        {
            var userId = _userManager.GetUserId(User);

            if (userId == null)
            {
                return RedirectToAction("Login", "Account");
            }


            foreach (var reviewViewModel in model.Reviews)
            {
                var review = new Review
                {
                    AuctionID = reviewViewModel.AuctionID,
                    UserID = int.Parse(userId),
                    Title = reviewViewModel.Title,
                    Description = reviewViewModel.Description,
                    IsPositive = reviewViewModel.IsPositive
                };

                _reviewService.Create(review);
            }

            return RedirectToAction("UserOrders", "Order");


            return View(model);
        }


    }
}

MVCAuctionPortal/Views/Auction/AddReviews.cshtml
@model MVCAuctionPortal.ViewModels.OrderReviewsViewModel
@{
    ViewBag.Title = "Add Reviews";
}

<h2>Add Reviews</h2>

<form asp-controller="Auction" asp-action="AddReviews" method="post">
    <input type="hidden" asp-for="OrderId" />
    @for (int i = 0; i < Model.Reviews.Count; i++)
    {
        <h4>Review for @Model.Reviews[i].AuctionName</h4>
        <input type="hidden" asp-for="Reviews[i].AuctionID" />
        <div class="form-group">
            <label asp-for="Reviews[i].Title"></label>
            <input asp-for="Reviews[i].Title" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="Reviews[i].Description"></label>
            <textarea asp-for="Reviews[i].Description" class="form-control"></textarea>
        </div>
        <div class="form-group">
            <label asp-for="Reviews[i].IsPositive">Positive</label>
            <input asp-for="Reviews[i].IsPositive" type="checkbox" />
        </div>
    }
    <button type="submit" class="btn btn-primary">Submit Reviews</button>
</form>

MVCAuctionPortal/Views/Auction/Create.cshtml
@model MVCAuctionPortal.Models.AuctionViewModel
@{
    ViewBag.Title = "Create Auction";
}
<form method="post" action="@Url.Action("Create", "Auction")">
    <div class="form-group">
        <label for="title">Title:</label>
        <input type="text" class="form-control" id="title" name="title" required>
    </div>
    <div class="form-group">
        <label for="endDate">End Date:</label>
        <input type="date" class="form-control" id="endDate" name="endDate" required>
    </div>
    <div class="form-group">
        <label for="price">Price:</label>
        <input type="number" class="form-control" id="price" name="price" required>
    </div>
    <div class="form-group">
        <label for="pieces">Pieces:</label>
        <input type="number" class="form-control" id="pieces" name="pieces" required>
    </div>
    <div class="form-group">
        <label for="SubCategoryID">SubCategory:</label>
        <select class="form-control" id="SubCategoryID" name="SubCategoryID" required>
            @foreach (var subCategory in Model.SubCategories)
            {
                <option value="@subCategory.SubCategoryID">@subCategory.Name</option>
            }
        </select>
    </div>
    <div class="form-group">
        <label for="itemID">Item:</label>
        <select class="form-control" id="itemID" name="itemID" required>
            <option value="">-- Select Item --</option>
            <option value="0">-- Add New --</option>
            @foreach (var item in Model.Items)
            {
                <option value="@item.ItemID">@item.Name</option>
            }
        </select>
    </div>

    <div class="form-group" id="newItemDiv" style="display:none">
        <label for="NewItemName">New Item Name:</label>
        <input type="text" class="form-control" id="NewItemName" name="NewItemName">

        <label for="NewItemDescription">Description:</label>
        <textarea class="form-control" id="NewItemDescription" name="NewItemDescription"></textarea>

        <label for="NewItemManufacturer">Manufacturer:</label>
        <input type="text" class="form-control" id="NewItemManufacturer" name="NewItemManufacturer">

        <label for="NewItemCondition">Condition:</label>
        <input type="text" class="form-control" id="NewItemCondition" name="NewItemCondition">

        <label for="NewItemModel">Model:</label>
        <input type="text" class="form-control" id="NewItemModel" name="NewItemModel">

        <label for="NewItemOther">Other:</label>
        <input type="text" class="form-control" id="NewItemOther" name="NewItemOther">
    </div>


    <div class="form-group">
        <label for="warrantyID">Warranty:</label>
        <select class="form-control" id="warrantyID" name="warrantyID" required>
            @foreach (var warranty in Model.Warranties)
            {
                <option value="@warranty.WarrantyID">@warranty.Name</option>
            }
        </select>
    </div>
    <div class="form-group">
        <label for="imageURL">Image URL:</label>
        <input type="url" class="form-control" id="imageURL" name="imageURL" required>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
@section Scripts
    {
    <script>
        document.getElementById("itemID").addEventListener("change", function () {
            var newItemDiv = document.getElementById("newItemDiv");
            if (this.value == "0") {
                newItemDiv.style.display = "block";
            } else {
                newItemDiv.style.display = "none";
            }
        });
    </script>
}

MVCAuctionPortal/Views/Auction/DeleteConfirmation.cshtml
@model AuctionPortal.Models.Auction

@{
    ViewData["Title"] = "Delete Confirmation";
}

<h2>Delete Confirmation</h2>
<p>Are you sure you want to delete this auction?</p>

<div class="row">
    <div class="col-md-6">
        <dl class="row">
            <dt class="col-md-4">Title:</dt>
            <dd class="col-md-8">@Model.Title</dd>

            <dt class="col-md-4">Description:</dt>
            <dd class="col-md-8">@Model.Item.Description</dd>

            <dt class="col-md-4">Seller:</dt>
            <dd class="col-md-8"><a href="/company/GetByUserID/@Model.UserID">@Model.UserID</a></dd>

            <dt class="col-md-4">Category:</dt>
            <dd class="col-md-8">@Model.SubCategory.Name</dd>
        </dl>
    </div>
    <div class="col-md-6">
        <img src="@Model.ImageURL" alt="@Model.Title" class="img-thumbnail">
    </div>
</div>

<div class="form-group">
    <form asp-action="Delete" asp-route-id="@Model.ItemID" method="post">
        <input type="hidden" asp-for="ItemID" />
        <button type="submit" class="btn btn-danger">Delete</button>
        <a asp-action="Index" class="btn btn-secondary">Cancel</a>
    </form>
</div>

MVCAuctionPortal/Views/Auction/Details.cshtml
@model AuctionPortal.Models.Item
@using AuctionPortal.Models
@{
    ViewData["Title"] = "Item Details";
    var reviews = ViewData["Reviews"] as List<Review>;
    var imageUrl = ViewData["ImageUrl"] as string;
}

<style>
    .item-image {
        max-width: 100%;
        max-height: 400px;
    }
</style>

<div class="row">
    <div class="col-md-6">
        <h2>@Model.Name</h2>
        <hr />
        <dl class="row">
            <dt class="col-sm-3">Description</dt>
            <dd class="col-sm-9">@Model.Description</dd>

            <dt class="col-sm-3">Manufacturer</dt>
            <dd class="col-sm-9">@Model.Manufacturer</dd>

            <dt class="col-sm-3">Condition</dt>
            <dd class="col-sm-9">@Model.Condition</dd>

            <dt class="col-sm-3">Model</dt>
            <dd class="col-sm-9">@Model.Model</dd>

            <dt class="col-sm-3">Other</dt>
            <dd class="col-sm-9">@Model.Other</dd>
        </dl>
        <h3>Opinie</h3>
        @if (reviews != null && reviews.Count > 0)
        {
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>Tytuł</th>
                    <th>Opis</th>
                    <th>Pozytywna</th>
                </tr>
                </thead>
                <tbody>
                @foreach (var review in reviews)
                {
                    <tr>
                        <td>@review.Title</td>
                        <td>@review.Description</td>
                        <td>@(review.IsPositive ? "Tak" : "Nie")</td>
                    </tr>
                }
                </tbody>
            </table>
        }
        else
        {
            <p>Brak opinii dla tego przedmiotu.</p>
        }
    </div>
    <div class="col-md-6">
        <img src="@imageUrl" alt="@Model.Name" class="img-fluid mb-3 item-image" />
    </div>
</div>

MVCAuctionPortal/Views/Auction/Edit.cshtml
@using AuctionPortal.Models
@model AuctionPortal.Models.Auction

@{
    ViewData["Title"] = "Auction Editing";
}

<form method="post" action="@Url.Action("Edit", "Auction")">

    <input type="hidden" name="AuctionID" value="@Model.AuctionID" />
    <input type="hidden" name="UserID" value="@Model.UserID" />


    <div class="form-group">
        <label for="Title">Title:</label>
        <input type="text" class="form-control" id="Title" name="Title" value="@Model.Title" required>
    </div>
    <div class="form-group">
        <label for="Description">Description:</label>
        <input type="text" class="form-control" id="Description" name="Item.Description" value="@Model.Item.Description" required>
    </div>
    <div class="form-group">
        <label for="EndDate">End Date:</label>
        <input type="date" class="form-control" id="EndDate" name="EndDate" value="@Model.EndDate" required>
    </div>
    <div class="form-group">
        <label for="Price">Price:</label>
        <input type="number" class="form-control" id="Price" name="Price" value="@Model.Price" required>
    </div>
    <div class="form-group">
        <label for="Pieces">Pieces:</label>
        <input type="number" class="form-control" id="Pieces" name="Pieces" value="@Model.Pieces" required>
    </div>
    <div class="form-group">
        <label for="SubCategoryID">Category ID:</label>
        <input type="number" class="form-control" id="SubCategoryID" name="SubCategoryID" value="@Model.SubCategoryID" required>
    </div>
    <div class="form-group">
        <label for="ItemID">Item ID:</label>
        <input type="number" class="form-control" id="ItemID" name="ItemID" value="@Model.ItemID" required>
    </div>
    <div class="form-group">
        <label for="WarrantyID">Warranty ID:</label>
        <input type="number" class="form-control" id="WarrantyID" name="WarrantyID" value="@Model.WarrantyID" required>
    </div>
    <div class="form-group">
        <label for="ImageURL">Image URL:</label>
        <input type="url" class="form-control" id="ImageURL" name="ImageURL" value="@Model.ImageURL" required>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

MVCAuctionPortal/Views/Auction/Index.cshtml
@model IEnumerable<AuctionPortal.Models.AuctionAndWarrantyViewModel>

@{
    ViewData["Title"] = "List of Auctions";
}

<style>
    .card {
        display: flex;
        flex-direction: column;
        justify-content: space-between;
        height:90%;
        background-color: #f8f9fa;
        border: 1px solid #dee2e6;
        border-radius: .25rem;
        transition: box-shadow .15s ease;
    }

        .card:hover {
            box-shadow: 0 0.5rem 1rem rgba(0, 0, 0, 0.15);
        }

        .card img {
            width: 100%;
            height: 100%;
            max-width: 100%;
            max-height: 80%;
            object-fit: contain;
            display: block;
            margin: auto;
            position: relative;
            top: 50%;
            transform: translateY(-50%);
        }


    .card-body {
        height: auto;
        overflow-y: auto;
        flex-grow: 1;
        display: flex;
        flex-direction: column;
        justify-content: space-between;
    }

    .card-container {
        position: relative;
        height: 500px;
        margin-bottom: 50px;
    }

    .card-footer {
        position: absolute;
        bottom: 0;
        left: 0;
        right: 0;
        margin-top: auto;
        background-color: transparent;
        border-top: 1px solid #dee2e6;
    }

    .row.equal-height > .col-md-4 {
        display: flex;
        flex-direction: column;
    }

    .card-header {
        background-color: #17a2b8;
        padding: .75rem 1.25rem;
        margin-bottom: 0;
        font-weight: 500;
    }


    .add-to-basket-form {
        display: flex;
    }

        .add-to-basket-form .form-control {
            width: 35%;
            border-top-left-radius: 0;
            border-bottom-left-radius: 0;
        }

        .add-to-basket-form .btn {
            width: 65%;
            border-top-right-radius: 0;
            border-bottom-right-radius: 0;
        }
    
    .small-btn {
        font-size: 0.9rem;
        padding: 0.25rem 0.5rem;
    }
</style>

<div class="container mt-3">
    <div class="row">
        @foreach (var item in Model)
        {
            var auction = item.Auction;
            var warranty = item.Warranty;
            <div class="col-md-4 col-xs-6 border-primary mb-3">
                <div class="card-container">
                    <div class="card mb-3">
                        <div class="row g-0">
                            <div class="col-md-12">
                                <div class="card-header text-white">
                                    <h5 class="card-title mb-0">@auction.Title</h5>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <img src="@auction.ImageURL" width="100%" alt="@auction.Title">
                            </div>
                            <div class="col-md-6">
                                <div class="card-body">
                                    <p class="card-text d-none d-md-block"><b>Description: </b>@auction.Item.Description</p>
                                    <p class="card-text d-none d-md-block"><b>Warranty: </b>@warranty.Description</p>
                                    <p class="card-text d-none d-md-block"><b>Category: </b>@auction.SubCategory.Name</p>
                                    <p class="card-text d-none d-md-block"><b>Price: </b>@auction.Price.ToString() $</p>
                                    <p class="card-text d-none d-md-block">
                                        <b>Status: </b>
                                        @if (DateTime.Now >= auction.DateOfIssue && DateTime.Now <= auction.EndDate && auction.Pieces > 0)
                                        {
                                            <span class="badge bg-success d-none d-md-block">AVAILABLE</span>
                                        }
                                        else if (DateTime.Now > auction.EndDate || auction.Pieces == 0)
                                        {
                                            <span class="badge bg-danger d-none d-md-block">ENDED</span>
                                        }
                                        else
                                        {
                                            <span class="badge bg-primary d-none d-md-block ">UPCOMING</span>
                                        }
                                    </p>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="card-footer mt-auto">
                                    <div class="row">
                                        <div class="col-6 mb-2">
                                            <a class="btn btn-outline-primary w-100 small-btn" asp-action="Details" asp-route-id="@auction.ItemID">
                                                <i class="bi bi-eye-fill"></i> Show Details
                                            </a>
                                        </div>
                                        <div class="col-6 mb-2">
                                            <form method="post" asp-controller="Basket" asp-action="AddToBasket" class="add-to-basket-form">
                                                <input type="hidden" name="auctionId" value="@auction.AuctionID" />
                                                <button type="submit" class="btn btn-success small-btn @((DateTime.Now > auction.EndDate) ? "disabled" : "")">
                                                    <i class="bi bi-cart-plus"></i> Add to Cart
                                                </button>
                                                <input type="number" class="form-control form-control-sm" name="quantity" min="1" max="@auction.Pieces" value="1" style="width: 50px;" />
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>

</div>

MVCAuctionPortal/Views/Auction/SellerAuctionList.cshtml
@model IEnumerable<AuctionPortal.Models.Auction>

@{
    ViewData["Title"] = "List of Auctions";
}
<style>
    .card {
        display: flex;
        flex-direction: column;
        justify-content: space-between;
        height: 100%;
    }

    .card img {
        max-width: 100%;
        max-height: 80%;
        object-fit: contain;
    }

    .card-body {
        height: auto;
        overflow-y: auto;
    }

    .card-container {
        position: relative;
        height: 450px;
        margin-bottom: 50px;
    }

    .card-footer {
        position: absolute;
        bottom: 0;
        left: 0;
        right: 0;
        margin-top: auto; 
    }
</style>
<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-md-4 col-xs-6 border-primary mb-3">
            <div class="card-container">
                <div class="card mb-3" style="max-width: 540px;">
                <div class="row g-0 ">
                    <div class="col-md-12">
                        <div class="card-header text-white bg-info">
                            <p class="card-text">
                                <h5 class="card-title">
                                    @item.Title
                                </h5>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <img src="@item.ImageURL" width="100%" alt="@item.Title">
                    </div>
                    <div class="col-md-6">
                        <div class="card-body">
                            <p class="card-text">@item.Item.Description</p>
                            <p class="card-text"><b>Seller: </b><a href="/company/GetByUserID/@item.UserID">@item.UserID</a></p>
                            <p class="card-text"><b>Category: </b>@item.SubCategory.Name</p>
                            <p class="card-text"><b>Start Date: </b>@item.DateOfIssue.ToString("dd MMM yyyy")</p>
                            <p class="card-text ">
                                <b>Status: </b>
                                @if (DateTime.Now >= item.DateOfIssue && DateTime.Now <= item.EndDate)
                                {
                                    <span class="badge bg-success text-white">AVAILABLE</span>
                                }
                                else if (DateTime.Now > item.EndDate)
                                {
                                    <span class="badge bg-danger text-white">ENDED</span>
                                }
                                else
                                {
                                    <span class="badge bg-primary text-white">UPCOMING</span>
                                }
                            </p>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="card-footer mt-auto">
                            <div class="row">
                                <div class="col-6 mb-2">
                                    <a class="btn btn-outline-primary w-100" asp-action="Edit" asp-route-id="@item.ItemID">
                                        <i class="bi bi-pencil-fill"></i> Edit
                                    </a>
                                </div>
                                <div class="col-6 mb-2">
                                    <a class="btn btn-outline-danger w-100" asp-action="DeleteConfirmation" asp-route-id="@item.ItemID">
                                        <i class="bi bi-trash-fill"></i> Delete
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                </div>
            </div>
        </div>
    }
</div>