MVCAuctionPortal/Models/Warranty.cs
using System.ComponentModel.DataAnnotations;

namespace AuctionPortal.Models
{
    public class Warranty
    {
        [Key]
        [Required]
        public int WarrantyID { get; set; }
        public string Name { get; set; }
        public int Durantion { get; set; }
        public string Description { get; set; }
    }
}

MVCAuctionPortal/Controllers/WarrantyController.cs
using AuctionPortal.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ServicesAndInterfacesLibary.Services;

namespace MVCAuctionPortal.Controllers
{
    public class WarrantyController : Controller
    {
        private readonly IWarrantyService _warrantyService;
        public WarrantyController(IWarrantyService warrantyService)
        {
            _warrantyService = warrantyService;
        }
        [Authorize(Roles = "Seller,Admin")]

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [Authorize(Roles = "Seller,Admin")]

        public IActionResult Create(Warranty warranty)
        {
            _warrantyService.Create(warranty);
            return RedirectToAction("ListOfWarranties");
        }


        [Authorize(Roles = "Seller,Admin")]

        public IActionResult Edit([FromRoute] int id)
        {
            var warranty = _warrantyService.GetWarrantyById(id);
            return View(warranty);
        }
        [Authorize(Roles = "User,Seller,Admin")]

        public IActionResult ListOfWarranties()
        {
            var warranty = _warrantyService.GetAllWarranties();
            return View(warranty);
        }
        [Authorize(Roles = "Seller,Admin")]

        [HttpPost]
        public IActionResult Edit(Warranty warranty)
        {
            _warrantyService.Update(warranty);
            return RedirectToAction("ListOfWarranties");
        }

        [HttpPost]
        public IActionResult Delete([FromRoute] int id)
        {
            _warrantyService.Delete(id);
            return RedirectToAction("ListOfWarranties");
        }
    }
}

MVCAuctionPortal/Views/Warranty/Create.cshtml
@model AuctionPortal.Models.Warranty

<form method="post" action="@Url.Action("Create", "Warranty")" class="form-horizontal" role="form">
    @Html.AntiForgeryToken()

    <div class="form-group">
        <label for="Name" class="control-label col-md-2">Name:</label>
        <div class="col-md-10">
            <input type="text" class="form-control" id="Name" name="Name" required>
            @Html.ValidationMessageFor(model => model.Name)
        </div>
    </div>

    <div class="form-group">
        <label for="Duration" class="control-label col-md-2">Duration:</label>
        <div class="col-md-10">
            <input type="number" class="form-control" id="Duration" name="Duration"  required>
            @Html.ValidationMessageFor(model => model.Durantion)
        </div>
    </div>

    <div class="form-group">
        <label for="Description" class="control-label col-md-2">Description:</label>
        <div class="col-md-10">
            <textarea class="form-control" id="Description" name="Description" required></textarea>
            @Html.ValidationMessageFor(model => model.Description)
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </div>
</form>

MVCAuctionPortal/Views/Warranty/Edit.cshtml
@model AuctionPortal.Models.Warranty

<form method="post" action="@Url.Action("Edit", "Warranty")" class="form-horizontal" role="form">
    <input type="hidden" name="WarrantyID" value="@Model.WarrantyID" />

    <div class="form-group">
        <label for="Name" class="control-label col-md-2">Name:</label>
        <div class="col-md-10">
            <input type="text" id="Name" name="Name" class="form-control" value="@Model.Name" />
        </div>
    </div>

    <div class="form-group">
        <label for="Duration" class="control-label col-md-2">Duration:</label>
        <div class="col-md-10">
            <input type="number" id="Durantion" name="Durantion" class="form-control" value="@Model.Durantion" />
        </div>
    </div>

    <div class="form-group">
        <label for="Description" class="control-label col-md-2">Description:</label>
        <div class="col-md-10">
            <textarea id="Description" name="Description" class="form-control">@Model.Description</textarea>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button type="submit" class="btn btn-default">Save</button>
        </div>
    </div>
</form>

MVCAuctionPortal/Views/Warranty/ListOfWarranties.cshtml
@model IEnumerable<AuctionPortal.Models.Warranty>

<table class="table table-striped table-bordered">
    <thead>
    <tr>
        <th>Name</th>
        <th>Duration</th>
        <th>Description</th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var warranty in Model)
    {
        <tr>
            <td>@warranty.Name</td>
            <td>@warranty.Durantion</td>
            <td>@warranty.Description</td>
            <td>
                <a href="@Url.Action("Edit", "Warranty", new { id = warranty.WarrantyID })" class="btn btn-primary">Edit</a>
                <form method="post" action="@Url.Action("Delete", "Warranty", new { id = warranty.WarrantyID })" onsubmit="return confirm('Are you sure you want to delete this item?');" style="display:inline;">
                    @Html.AntiForgeryToken()
                    <input type="submit" value="Delete" class="btn btn-danger" />
                </form>


            </td>
        </tr>
    }
    </tbody>
</table>